export const companyInfos = [
  {
    id: 1,
    unitCompany: {
      name: 'Microsoft.KR',
      num: '120-81-0248',
      phone: '02-3151-7000',
      address: '서울특별시 종로구 종로 1길 50. 더케이트윈타워 A동 11층',
      siteUrl: 'https://www.microsoft.com/ko-kr',
      head: 'CHO WONWOO',
      note: '',
    },
  },
  {
    id: 2,
    unitCompany: {
      name: 'Microsoft.KR',
      num: '120-81-0248',
      phone: '02-3151-7000',
      address: '서울특별시 종로구 종로 1길 50. 더케이트윈타워 A동 11층',
      siteUrl: 'https://www.microsoft.com/ko-kr',
      head: 'CHO WONWOO',
      note: '',
    },
  },
  {
    id: 3,
    unitCompany: {
      name: 'Microsoft.KR',
      num: '120-81-0248',
      phone: '02-3151-7000',
      address: '서울특별시 종로구 종로 1길 50. 더케이트윈타워 A동 11층',
      siteUrl: 'https://www.microsoft.com/ko-kr',
      head: 'CHO WONWOO',
      note: '',
    },
  },
];

export const assetInfos = [
  {
    id: 1,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '응용SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 2,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '응용SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 3,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '시스템인프라SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 4,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '시스템인프라SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },

  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '증권',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '증권',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
];
export const assetHistoryInfos = [
  {
    id: 1,
    unitHistory: {
      manager: '시스템 관리자',
      activity: '필드 변경',
      date: '2024-01-24 11:47',
      descrip: 'State: In Use',
    },
  },
  {
    id: 2,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 2,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 3,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 4,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
];
