export const companyInfos = [
  {
    id: 1,
    unitCompany: {
      name: 'Microsoft.KR',
      num: '120-81-0248',
      phone: '02-3151-7000',
      address: '서울특별시 종로구 종로 1길 50. 더케이트윈타워 A동 11층',
      siteUrl: 'https://www.microsoft.com/ko-kr',
      head: 'CHO WONWOO',
      note: '',
    },
  },
  {
    id: 2,
    unitCompany: {
      name: 'Polaris Office Corp',
      num: '220-81-43747',
      phone: '+82-2-537-0538',
      address: '서울특별시 구로구 디지털로31길 12, 15층(구로동)',
      siteUrl: 'https://www.polarisoffice.com/ko/#',
      head: '지준경',
      note: '',
    },
  },
];

export const assetInfos = [
  {
    id: 'A000001',
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '응용SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 'A000002',
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '응용SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 'A000003',
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '시스템인프라SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 'A000004',
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '은행',
      category: '시스템인프라SW',
      cost: '₩655,447,111.8469',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 'A000005',
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 'A000006',
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '부동산',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },

  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '증권',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '김민기',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 5,
    unitAsset: {
      name: 'Microsoft Word 2010',
      division: '내부자산',
      tag: '증권',
      category: '시스템인프라SW',
      cost: '₩369,447,777.3232',
      version: 'v1.0',
      manager: '박서연',
      manual: '',
      company: 'Microsoft',
      date: '2023-02-13',
    },
  },
  {
    id: 'A000079',
    unitAsset: {
      name: 'AhnLab V3 Endpoint Security 9.0',
      division: '내부자산',
      tag: '은행',
      category: '응용SW',
      cost: '₩42,000',
      version: '',
      manager: '김지은',
      manual: '',
      company: 'AhnLab',
      date: '2023-02-14',
    },
  },
];
export const assetHistoryInfos = [
  {
    id: 1,
    unitHistory: {
      manager: '시스템 관리자',
      activity: '필드 변경',
      date: '2024-01-24 11:47',
      descrip: 'State: In Use',
    },
  },
  {
    id: 2,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 2,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 3,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 4,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
];
export const contractInfos = [
  {
    id: 'C000001',
    unitContract: {
      contractNum: 'C000001',
      name: 'TV Calibration Software',
      assetName: 'Microsoft Word 2010',
      company: 'SAMSUNG',
      manager: '조익현',
      cost: '₩285,447,111.8469',
      registrant: '김의진',
      startDate: '2022-09-25',
      endDate: '2026-09-25',
      File: '',
      Memo: '비밀',
      supplyLicense: 'SaaS 라이선스',
      supplyLicenseDetail:
        '접속 url : http://example.com/access1 \n 버전 : 2.0.1',
      periodLicense: '영구 라이선스',
      periodLicenseDetail: '',
      userLicense: '코어 라이선스',
      userLicenseDetail: 'core 수 : 8개',
    },
  },
  {
    id: 'C000002',
    unitContract: {
      contractNum: 'C000002',
      name: '자동차 보험 관리 시스템 계약',
      assetName: '자동차 보험 관리 시스템',
      company: 'KB손해 보험',
      manager: '오은비',
      cost: '₩1,000,000',
      registrant: '김의진',
      startDate: '2024-02-15',
      endDate: '2025-02-14',
      File: '',
      Memo: '',
      supplyLicense: 'SaaS 라이선스',
      supplyLicenseDetail:
        '접속 url : http://example.com/access1 \n 버전 : 2.0.1',
      periodLicense: '구독 라이선스',
      periodLicenseDetail: '시작일 : 2024-02-15 \n 종료일: 2024-02-14',
      userLicense: '동시 사용자 수 라이선스',
      userLicenseDetail: '최대 사용자수 : 200',
    },
  },
];
export const contractHistoryInfos = [
  {
    id: 1,
    unitHistory: {
      manager: '시스템 관리자',
      activity: '필드 변경',
      date: '2024-01-24 11:47',
      descrip: 'State: In Use',
    },
  },
  {
    id: 2,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 2,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 3,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
  {
    id: 4,
    unitHistory: {
      manager: '담당자',
      activity: '계약 체결',
      date: '2024-01-22 11:47',
      descrip: '일련번호: MS9323',
    },
  },
];

// {
//   id: 'C000002',
//   unitContract: {
//     name: 'TV Calibration Software',
//     assetName: 'Microsoft Word 2010',
//     company: 'SAMSUNG',
//     manager: '김의진',
//     cost: '₩285,447,111.8469',
//     registrant: '조익현',
//     startDate: '2022-09-25',
//     endDate: '2026-09-25',
//     File: '',
//     Memo: '비밀',
//   },
// },
// {
//   id: 'C000003',
//   unitContract: {
//     name: 'TV Calibration Software',
//     assetName: 'Microsoft Word 2010',
//     company: 'SAMSUNG',
//     manager: '김의진',
//     cost: '₩285,447,111.8469',
//     registrant: '조익현',
//     startDate: '2022-09-25',
//     endDate: '2026-09-25',
//     File: '',
//     Memo: '비밀',
//   },
// },
// {
//   id: 'C000004',
//   unitContract: {
//     name: 'TV Calibration Software',
//     assetName: 'Microsoft Word 2010',
//     company: 'SAMSUNG',
//     manager: '김의진',
//     cost: '₩285,447,111.8469',
//     registrant: '조익현',
//     startDate: '2022-09-25',
//     endDate: '2026-09-25',
//     File: '',
//     Memo: '비밀',
//   },
// },
// {
//   id: 'C000005',
//   unitContract: {
//     name: 'TV Calibration Software',
//     assetName: 'Microsoft Word 2010',
//     company: 'SAMSUNG',
//     manager: '김의진',
//     cost: '₩285,447,111.8469',
//     registrant: '조익현',
//     startDate: '2022-09-25',
//     endDate: '2026-09-25',
//     File: '',
//     Memo: '비밀',
//   },
// },
